name: ShulkerCrate
version: '${project.version}'
main: me.zombie_striker.shulkercrate.ShulkerCrate
api-version: 1.19
commands:
  shulkercrate:
    description: "ShulkerCrate commands"
    aliases:
      - "sc"
      - "crate"
  keys:
    description: "View Keys"
permissions:
  shulkercrates.commands.placecrate:
    description: "Allows players to use the /sc placecrate command"
  shulkercrates.destroycrates:
    description: "Allows players to destroy crates"
  shulkercrates.commands.addprize:
    description: "Adds prizes using commands."